const secondHandItems = [
  {
    category: 'car',
    name: 'Tata Nexon 2020',
    image: 'car5.jpg',
    price: 850000,
    description: 'Top model, low mileage, excellent condition.',
    address: 'Delhi, India',
    time: '1 month ago',
  },
  {
    category: 'bike',
    name: 'Yamaha FZ-S 2019',
    image: 'bike5.jpg',
    price: 80000,
    description: 'Black color, well-maintained, showroom condition.',
    address: 'Mumbai, India',
    time: '3 weeks ago',
  },
  {
    category: 'furniture',
    name: 'L-Shaped Sofa Set',
    image: 'furniture5.jpg',
    price: 55000,
    description: 'Modern design, premium fabric, 5-seater.',
    address: 'Bangalore, India',
    time: '2 weeks ago',
  },
  {
    category: 'car',
    name: 'Hyundai Creta 2019',
    image: 'car6.jpg',
    price: 1100000,
    description: 'Automatic transmission, well-maintained, single owner.',
    address: 'Chennai, India',
    time: '4 days ago',
  },
  {
    category: 'bike',
    name: 'KTM Duke 200',
    image: 'bike6.jpg',
    price: 150000,
    description: 'Orange color, powerful engine, great condition.',
    address: 'Kolkata, India',
    time: '2 weeks ago',
  },
  {
    category: 'furniture',
    name: 'Vintage Wooden Desk',
    image: 'furniture6.jpg',
    price: 20000,
    description: 'Antique piece, sturdy construction, spacious drawers.',
    address: 'Hyderabad, India',
    time: '1 month ago',
  },
  {
    category: 'car',
    name: 'Maruti Suzuki Alto 800',
    image: 'car7.jpg',
    price: 300000,
    description: 'Silver color, low mileage, perfect for city drive.',
    address: 'Pune, India',
    time: '3 weeks ago',
  },
  {
    category: 'bike',
    name: 'Honda CB Unicorn 150',
    image: 'bike7.jpg',
    price: 60000,
    description: 'Black color, reliable commuter bike, great mileage.',
    address: 'Jaipur, India',
    time: '2 days ago',
  },
  {
    category: 'furniture',
    name: 'Recliner Sofa Set',
    image: 'furniture7.jpg',
    price: 80000,
    description: 'Leather finish, electric recliners, luxury comfort.',
    address: 'Ahmedabad, India',
    time: '1 week ago',
  },
  {
    category: 'car',
    name: 'Volkswagen Polo 2017',
    image: 'car8.jpg',
    price: 600000,
    description: 'White color, well-maintained, premium hatchback.',
    address: 'Chandigarh, India',
    time: '4 days ago',
  },
  {
    category: 'bike',
    name: 'Suzuki Access 125',
    image: 'bike8.jpg',
    price: 45000,
    description: 'Blue color, good condition, ideal for daily commute.',
    address: 'Lucknow, India',
    time: '3 weeks ago',
  },
  {
    category: 'furniture',
    name: 'Rustic Wooden Coffee Table',
    image: 'furniture8.jpg',
    price: 25000,
    description: 'Handcrafted, unique design, adds character to any room.',
    address: 'Nagpur, India',
    time: '2 days ago',
  },
  {
    category: 'car',
    name: 'Ford EcoSport 2016',
    image: 'car9.jpg',
    price: 700000,
    description: 'Black color, well-maintained, powerful SUV.',
    address: 'Delhi, India',
    time: '1 week ago',
  },
  {
    category: 'bike',
    name: 'Bajaj Avenger Cruise 220',
    image: 'bike9.jpg',
    price: 90000,
    description: 'Cruise series, comfortable ride, long-distance cruiser.',
    address: 'Mumbai, India',
    time: '2 weeks ago',
  },
  {
    category: 'furniture',
    name: 'Modern TV Unit',
    image: 'furniture9.jpg',
    price: 35000,
    description: 'Sleek design, ample storage, accommodates large TVs.',
    address: 'Bangalore, India',
    time: '3 days ago',
  },
  {
    category: 'car',
    name: 'Mahindra XUV500 2015',
    image: 'car10.jpg',
    price: 900000,
    description: 'SUV, well-maintained, spacious interior.',
    address: 'Chennai, India',
    time: '3 weeks ago',
  },
  {
    category: 'bike',
    name: 'Hero Passion Pro',
    image: 'bike10.jpg',
    price: 55000,
    description: 'Red color, fuel-efficient, reliable commuter bike.',
    address: 'Kolkata, India',
    time: '4 days ago',
  },
  {
    category: 'furniture',
    name: 'Vintage Armchair',
    image: 'furniture10.jpg',
    price: 18000,
    description: 'Classic design, comfortable seating, excellent condition.',
    address: 'Hyderabad, India',
    time: '1 week ago',
  },
  {
    category: 'car',
    name: 'Renault Kwid 2021',
    image: 'car11.jpg',
    price: 550000,
    description: 'Latest model, low mileage, compact hatchback.',
    address: 'Pune, India',
    time: '2 days ago',
  },
  {
    category: 'bike',
    name: 'TVS Jupiter',
    image: 'bike11.jpg',
    price: 60000,
    description: 'Grey color, good mileage, ideal for city rides.',
    address: 'Jaipur, India',
    time: '3 weeks ago',
  },
  {
    category: 'furniture',
    name: 'Modern Bookshelf',
    image: 'furniture11.jpg',
    price: 30000,
    description: 'Sleek design, adjustable shelves, perfect for home library.',
    address: 'Ahmedabad, India',
    time: '4 days ago',
  },
  {
    category: 'car',
    name: 'Chevrolet Beat 2018',
    image: 'car12.jpg',
    price: 350000,
    description: 'Grey color, well-maintained, compact hatchback.',
    address: 'Chandigarh, India',
    time: '1 week ago',
  },
  {
    category: 'bike',
    name: 'Honda Shine',
    image: 'bike12.jpg',
    price: 55000,
    description: 'Black color, good mileage, reliable commuter bike.',
    address: 'Lucknow, India',
    time: '2 days ago',
  },
  {
    category: 'furniture',
    name: 'Vintage Writing Desk',
    image: 'furniture12.jpg',
    price: 22000,
    description: 'Solid wood, classic design, perfect for home office.',
    address: 'Nagpur, India',
    time: '3 weeks ago',
  },
  {
    category: 'car',
    name: 'Hyundai Verna 2019',
    image: 'car13.jpg',
    price: 900000,
    description: 'White color, well-maintained, sedan.',
    address: 'Delhi, India',
    time: '4 days ago',
  },
  {
    category: 'bike',
    name: 'Bajaj Platina 100',
    image: 'bike13.jpg',
    price: 40000,
    description: 'Black color, good mileage, budget-friendly bike.',
    address: 'Mumbai, India',
    time: '1 week ago',
  },
  {
    category: 'furniture',
    name: 'Industrial Style Dining Table',
    image: 'furniture13.jpg',
    price: 40000,
    description: 'Metal frame, wooden top, seats 6 people comfortably.',
    address: 'Bangalore, India',
    time: '2 weeks ago',
  },
  {
    category: 'car',
    name: 'Ford Figo 2017',
    image: 'car14.jpg',
    price: 450000,
    description: 'Silver color, well-maintained, hatchback.',
    address: 'Chennai, India',
    time: '3 days ago',
  },
  {
    category: 'bike',
    name: 'Suzuki Gixxer SF',
    image: 'bike14.jpg',
    price: 85000,
    description: 'Blue color, sporty looks, excellent handling.',
    address: 'Kolkata, India',
    time: '2 weeks ago',
  },
  {
    category: 'furniture',
    name: 'Leather Recliner Chair',
    image: 'furniture14.jpg',
    price: 30000,
    description: 'Comfortable, luxurious, perfect for relaxation.',
    address: 'Hyderabad, India',
    time: '4 days ago',
  },
];

export default secondHandItems;
